version: '3.8'
services:
  mongo:
    image: mongo:8.0.0
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '5000:5000'
    environment:
      - MONGODB_ENDPOINT=mongodb://mongo:27017/api
      - SESSION_SECRET="djbfpsfvFJSDB"
      - PORT=5000
      - FRONTEND_URL=http://localhost:3000
      - JWT_SECRET="fewbfgwubfobibwepbvf"
    depends_on:
      - mongo
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - '3000:3000'
    depends_on:
      - server
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - client
      - server
volumes:
  mongo-data: