version: '3.8'

services:
  mongo:
    image: mongo:8.0.0
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    env_file:
      - ./server/src/.env
    environment:
      MONGODB_ENDPOINT: mongodb://mongo:27017/api
    ports:
      - '5000:5000'
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    env_file:
      - ./client/.env
    ports:
      - '3000:3000'
    depends_on:
      - server

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      - client
      - server

volumes:
  mongo-data:
